language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - cd ..
  - git clone git://github.com/uthando-cms/uthando.git
  - git clone git://github.com/uthando-cms/uthando-common.git
  - cp -R ./uthando-newsletter/test/composer.test.json ./uthando/composer.json
  - cd uthando
  - composer install
  - cp -R ../uthando-newsletter ./module/UthandoNewsletter
  - cp -R ../uthando-common ./module/UthandoCommon
  - cd module/UthandoNewsletter/test

script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  - php ../../../vendor/bin/phpunit

after_script:
  - cd ../
  - cp -R ../../vendor ./vendor
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then php vendor/bin/test-reporter --coverage-report=build/logs/clover.xml; fi

matrix:
  allow_failures:
    - php: hhvm
