<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoNewsletter\Module'                 => __DIR__ . '/Module.php',
    'UthandoNewsletter\Controller\Newsletter'  => __DIR__ . '/src/UthandoNewsletter/Controller/Newsletter.php',
    'UthandoNewsletter\Controller\Subscriber'  => __DIR__ . '/src/UthandoNewsletter/Controller/Subscriber.php',
    'UthandoNewsletter\Form\Newsletter'        => __DIR__ . '/src/UthandoNewsletter/Form/Newsletter.php',
    'UthandoNewsletter\Form\Subscriber'        => __DIR__ . '/src/UthandoNewsletter/Form/Subscriber.php',
    'UthandoNewsletter\Hydrator\Newsletter'    => __DIR__ . '/src/UthandoNewsletter/Hydrator/Newsletter.php',
    'UthandoNewsletter\Hydrator\Subscriber'    => __DIR__ . '/src/UthandoNewsletter/Hydrator/Subscriber.php',
    'UthandoNewsletter\InputFilter\Newsletter' => __DIR__ . '/src/UthandoNewsletter/InputFilter/Newsletter.php',
    'UthandoNewsletter\InputFilter\Subscriber' => __DIR__ . '/src/UthandoNewsletter/InputFilter/Subscriber.php',
    'UthandoNewsletter\Mapper\Newsletter'      => __DIR__ . '/src/UthandoNewsletter/Mapper/Newsletter.php',
    'UthandoNewsletter\Mapper\Subscriber'      => __DIR__ . '/src/UthandoNewsletter/Mapper/Subscriber.php',
    'UthandoNewsletter\Model\Newsletter'       => __DIR__ . '/src/UthandoNewsletter/Model/Newsletter.php',
    'UthandoNewsletter\Model\Subscriber'       => __DIR__ . '/src/UthandoNewsletter/Model/Subscriber.php',
    'UthandoNewsletter\Service\Newsletter'     => __DIR__ . '/src/UthandoNewsletter/Service/Newsletter.php',
    'UthandoNewsletter\Service\Subscriber'     => __DIR__ . '/src/UthandoNewsletter/Service/Subscriber.php',
);
