<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-newsletter/newsletter/edit'  => __DIR__ . '/view/uthando-newsletter/newsletter/edit.phtml',
    'uthando-newsletter/newsletter/index' => __DIR__ . '/view/uthando-newsletter/newsletter/index.phtml',
    'uthando-newsletter/subscriber/add'   => __DIR__ . '/view/uthando-newsletter/subscriber/add.phtml',
    'uthando-newsletter/subscriber/edit'  => __DIR__ . '/view/uthando-newsletter/subscriber/edit.phtml',
    'uthando-newsletter/subscriber/index' => __DIR__ . '/view/uthando-newsletter/subscriber/index.phtml',
    'uthando-newsletter/subscriber/list'  => __DIR__ . '/view/uthando-newsletter/subscriber/list.phtml',
);
