<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-newsletter/message/add'                    => __DIR__ . '/view/uthando-newsletter/message/add.phtml',
    'uthando-newsletter/message/edit'                   => __DIR__ . '/view/uthando-newsletter/message/edit.phtml',
    'uthando-newsletter/message/index'                  => __DIR__ . '/view/uthando-newsletter/message/index.phtml',
    'uthando-newsletter/message/list'                   => __DIR__ . '/view/uthando-newsletter/message/list.phtml',
    'uthando-newsletter/newsletter/add'                 => __DIR__ . '/view/uthando-newsletter/newsletter/add.phtml',
    'uthando-newsletter/newsletter/edit'                => __DIR__ . '/view/uthando-newsletter/newsletter/edit.phtml',
    'uthando-newsletter/newsletter/index'               => __DIR__ . '/view/uthando-newsletter/newsletter/index.phtml',
    'uthando-newsletter/newsletter/list'                => __DIR__ . '/view/uthando-newsletter/newsletter/list.phtml',
    'uthando-newsletter/subscriber/add-subscriber'      => __DIR__ . '/view/uthando-newsletter/subscriber/add-subscriber.phtml',
    'uthando-newsletter/subscriber/add'                 => __DIR__ . '/view/uthando-newsletter/subscriber/add.phtml',
    'uthando-newsletter/subscriber/edit'                => __DIR__ . '/view/uthando-newsletter/subscriber/edit.phtml',
    'uthando-newsletter/subscriber/error'               => __DIR__ . '/view/uthando-newsletter/subscriber/error.phtml',
    'uthando-newsletter/subscriber/index'               => __DIR__ . '/view/uthando-newsletter/subscriber/index.phtml',
    'uthando-newsletter/subscriber/list'                => __DIR__ . '/view/uthando-newsletter/subscriber/list.phtml',
    'uthando-newsletter/subscriber/update-subscription' => __DIR__ . '/view/uthando-newsletter/subscriber/update-subscription.phtml',
    'uthando-newsletter/template/add'                   => __DIR__ . '/view/uthando-newsletter/template/add.phtml',
    'uthando-newsletter/template/edit'                  => __DIR__ . '/view/uthando-newsletter/template/edit.phtml',
    'uthando-newsletter/template/index'                 => __DIR__ . '/view/uthando-newsletter/template/index.phtml',
    'uthando-newsletter/template/list'                  => __DIR__ . '/view/uthando-newsletter/template/list.phtml',
);
