<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-newsletter/newsletter/add'   => __DIR__ . '/view/uthando-newsletter/newsletter/add.phtml',
    'uthando-newsletter/newsletter/edit'  => __DIR__ . '/view/uthando-newsletter/newsletter/edit.phtml',
    'uthando-newsletter/newsletter/index' => __DIR__ . '/view/uthando-newsletter/newsletter/index.phtml',
    'uthando-newsletter/newsletter/list'  => __DIR__ . '/view/uthando-newsletter/newsletter/list.phtml',
);
