
<?php $this->headTitle('Edit Template') ?>
<?php $this->layout()->pageTitle = $this->translate('Edit Template');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<button type="submit" form="form-newsletter-template" data-toggle="tooltip" title="<?=$this->translate('Save');?>" class="btn btn-primary">
    <i class="fa fa-save"></i>
</button>
<a href="<?=$this->url('admin/newsletter/template');?>" data-toggle="tooltip" title="<?=$this->translate('Cancel');?>" class="btn btn-default">
    <i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-newsletter-template',
    'action' => $this->url('admin/newsletter/template/edit', [
        'id' => $this->model->getTemplateId(),
    ]),
]); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?=$this->translate('Edit Template');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->form($this->form);?>
    </div>
</div>
