
<?php $this->headTitle('Newsletter Template') ?>

<?php if (count($this->models) > 0): ?>
    <div class="panel panel-default">
        <table class="table table-hover table-bordered table-condensed">
            <thead>
            <tr>
                <th data-field="templateId">Id</th>
                <th data-field="name">Name</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $row \UthandoNewsletter\Model\Template */ ?>
            <?php foreach($this->models as $row): ?>
                <tr>
                    <td><?=$this->escapeHtml($row->getTemplateId()); ?></td>
                    <td><?=$this->escapeHtml($row->getName()); ?></td>
                    <td>
                        <?=$this->partial('uthando-admin/partial/edit-actions', [
                            'pk'		=> 'newsletterId',
                            'id'		=> $row->getTemplateId(),
                            'tableName'	=> 'newsletter-template',
                            'route'		=> 'admin/newsletter/template/edit',
                        ]);?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?=$this->paginationControl(
        $this->models,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'admin/newsletter/template/page']
    ); ?>

<?php else: ?>
    <h4>There are no Templates yet.</h4>
<?php endif; ?>