
<?php $this->headTitle('Add Message') ?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
    'form' 			=> $this->form,
    'formName'		=> 'Add Message',
    'postUrl'		=> $this->url('admin/newsletter/message/edit', [
        'action' => 'add',
    ]),
    'cancelUrl'     => $this->url('admin/newsletter/message'),
    'formWidth'     => 12,
    'formElements'	=> [
        'templateId', 'subject', 'params', 'message',
    ],
]); ?>