
<?php $this->headTitle('Add Newsletter Message') ?>
<?php $this->layout()->pageTitle = $this->translate('Add Newsletter Message');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<button type="submit" form="form-newsletter-message" data-toggle="tooltip" title="<?=$this->translate('Save');?>" class="btn btn-primary">
    <i class="fa fa-save"></i>
</button>
<a href="<?=$this->url('admin/newsletter/message');?>" data-toggle="tooltip" title="<?=$this->translate('Cancel');?>" class="btn btn-default">
    <i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-newsletter-message',
    'action' => $this->url('admin/newsletter/message/edit', [
        'action' => 'add',
    ]),
]); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?=$this->translate('Add Newsletter Message');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->form($this->form);?>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('textarea.editable-textarea').summernote({
            height: 300,
            toolbar: [
                ['style', ['style', 'bold', 'underline', 'clear']],
                ['font', ['fontname', 'fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
                ['insert', ['link', 'picture']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ]
        });
    });
</script>
