<?php $this->headTitle('Newsletter Message') ?>

<?php if (count($this->models) > 0): ?>
    <div class="panel panel-default">
        <table class="table table-hover table-bordered table-condensed">
            <thead>
            <tr>
                <th data-field="messageId">Id</th>
                <th data-field="subject">Subject</th>
                <th data-field="template">Template</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $row \UthandoNewsletter\Model\Message */ ?>
            <?php foreach($this->models as $row): ?>
                <tr>
                    <td><?=$this->escapeHtml($row->getMessageId()); ?></td>
                    <td><?=$this->escapeHtml($row->getSubject()); ?></td>
                    <td><?=$this->escapeHtml($row->getTemplate()->getName()); ?></td>
                    <td>
                        <?=$this->partial('uthando-admin/partial/edit-actions', [
                            'pk'		=> 'messageId',
                            'id'		=> $row->getMessageId(),
                            'tableName'	=> 'newsletter-message',
                            'route'		=> 'admin/newsletter/message/edit',
                        ]);?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?=$this->paginationControl(
        $this->models,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'admin/newsletter/template/page']
    ); ?>

<?php else: ?>
    <h4>There are no Messages yet.</h4>
<?php endif; ?>