
<?php if (count($this->models) > 0): ?>
    <div class="table-responsive">
        <table class="table table-hover table-bordered table-condensed sortable-table">
            <thead>
            <tr>
                <th data-field="messageId"><?=$this->translate('Messgae Id');?></th>
                <th data-field="newsletter"><?=$this->translate('Newsletter');?></th>
                <th data-field="subject"><?=$this->translate('Subject');?></th>
                <th data-field="template"><?=$this->translate('Template');?></th>
                <th><?=$this->translate('Actions');?></th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $row \UthandoNewsletter\Model\Message */ ?>
            <?php foreach($this->models as $row): ?>
                <tr>
                    <td><?=$this->escapeHtml($row->getMessageId()); ?></td>
                    <td><?=$this->escapeHtml($row->getNewsletter()->getName()); ?></td>
                    <td><?=$this->escapeHtml($row->getSubject()); ?></td>
                    <td><?=$this->escapeHtml($row->getTemplate()->getName()); ?></td>
                    <td>
                        <a href="<?=$this->url('admin/newsletter/message/edit', [
                            'action' => 'send',
                            'id' => $row->getMessageId(),
                        ]);?>" class="btn btn-primary">
                            <i class="fa fa-paper-plane-o"></i></a>&nbsp;
                        <a href="<?=$this->url('admin/newsletter/message/edit', [
                            'action' => 'preview',
                            'id' => $row->getMessageId(),
                        ]);?>" class="btn btn-default message-preview">
                            <i class="fa fa-eye"></i></a>&nbsp;
                        <?=$this->partial('uthando-admin/partial/edit-actions', [
                            'pk'		=> 'messageId',
                            'id'		=> $row->getMessageId(),
                            'tableName'	=> 'newsletter-message',
                            'route'		=> 'admin/newsletter/message/edit',
                        ]);?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?=$this->paginationControl(
        $this->models,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'admin/newsletter/template/page']
    ); ?>

<?php else: ?>
    <h4><?=$this->translate('There are no Messages yet.');?></h4>
<?php endif; ?>

<script>
    $('table').on('click', 'a.message-preview', function(e) {
        e.preventDefault();
        var url = $(this).attr('href');

        bootbox.dialog({
            size: 'large',
            title: "<?=$this->translate('Newsletter Message Preview');?>",
            message: '<iframe class="newsletter-preview" src="' + url + '"></iframe>',
            buttons: {
                main: {
                    label: "Close",
                    className: "btn-default"
                }
            }
        });
    });
</script>