
<?php $this->headTitle('Add Newsletter') ?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
    'form' 			=> $this->form,
    'formName'		=> 'Add Newsletter',
    'postUrl'		=> $this->url('admin/newsletter/edit', [
        'action' => 'add',
    ]),
    'cancelUrl'     => $this->url('admin/newsletter'),
    'formWidth'     => 6,
    'formElements'	=> [
        'name', 'description', 'visible',
    ],
]); ?>