
<?php $this->headTitle('Edit Newsletter') ?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
    'form' 			=> $this->form,
    'formName'		=> 'Edit Newsletter',
    'postUrl'		=> $this->url('admin/newsletter/edit', [
        'id' => $this->model->getNewsletterId(),
    ]),
    'cancelUrl'     => $this->url('admin/newsletter'),
    'formWidth'     => 6,
    'formElements'	=> [
        'name', 'description', 'visible', 'newsletterId',
    ],
]); ?>