
<?=$this->partial('uthando-admin/partial/search', [
    'name'			=> 'newsletter',
    'searchInputs'	=> [
        'Newsletters' => 'name-description',
    ],
]);?>

<div id="table-newsletter">
    <?=$this->partial('uthando-newsletter/newsletter/list', [
        'models' => $this->models
    ]); ?>
</div>


<script>
    $(document).ready(function(){
        $('#table-newsletter').dataGrid({
            url : 'newsletter/list',
            query: { sort : 'newsletterId' },
            searchForm : $('#search-newsletter'),
            paging : 'links',
            columnSort: true
        });
    });
</script>