
<?php
$menu = $this->uthandoNavigation('UthandoAdmin\Navigation')
    ->uthandoTbMenu()
    ->setUlClass('dropdown-menu')
    ->setOnlyActiveBranch(true)
    ->setRenderParents(false);

if ($this->menuPartial) {
    $menu->setPartial($this->menuPartial);
}
?>

<div class="dropdown pull-right">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
        Actions
        <span class="caret"></span>
    </button>
    <?=$menu;?>
</div>

<div class=""clearfix">&nbsp;</div>