
<?php $this->headTitle('Newsletter') ?>

<?php if (count($this->models) > 0): ?>
    <div class="panel panel-default">
        <table class="table table-hover table-bordered table-condensed">
            <thead>
            <tr>
                <th data-field="newsletterId">Id</th>
                <th data-field="name">Name</th>
                <th data-field="description">Description</th>
                <th data-field="visible">Visible</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $row \UthandoNewsletter\Model\Newsletter */ ?>
            <?php foreach($this->models as $row): ?>
                <?php $icon = ($row->isVisible()) ? 'check' : 'times'; ?>
                <tr>
                    <td><?=$this->escapeHtml($row->getNewsletterId()); ?></td>
                    <td><?=$this->escapeHtml($row->getName()); ?></td>
                    <td><?=$this->escapeHtml($row->getDescription()); ?></td>
                    <td><i class="fa fa-<?=$icon;?>"</i></td>
                    <td>
                        <?=$this->partial('uthando-admin/partial/edit-actions', [
                            'pk'		=> 'newsletterId',
                            'id'		=> $row->getNewsletterId(),
                            'tableName'	=> 'newsletter',
                            'route'		=> 'admin/newsletter/edit',
                        ]);?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?=$this->paginationControl(
        $this->models,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'admin/newsletter/page']
    ); ?>

<?php else: ?>
    <h4>There are no Newsletters yet.</h4>
<?php endif; ?>