
<?php $this->headTitle('Add Subscriber') ?>

<?php $this->form->get('subscribe')->setIncludeHidden(true);?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
    'form' 			=> $this->form,
    'formName'		=> 'Add Subscriber',
    'postUrl'		=> $this->url('admin/newsletter/subscriber/edit', [
        'action' => 'add',
    ]),
    'cancelUrl'     => $this->url('admin/newsletter/subscriber'),
    'formWidth'     => 6,
    'formElements'	=> [
        'name', 'email', 'subscribe',
    ],
]); ?>
