
<?php $this->headTitle('Edit Subscriber') ?>

<?php $this->form->get('subscribe')->setIncludeHidden(true);?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
    'form' 			=> $this->form,
    'formName'		=> 'Edit Subscriber',
    'postUrl'		=> $this->url('admin/newsletter/subscriber/edit', [
        'id' => $this->model->getSubscriberId(),
    ]),
    'cancelUrl'     => $this->url('admin/newsletter/subscriber'),
    'formWidth'     => 6,
    'formElements'	=> [
        'name', 'email', 'subscribe', 'subscriberId',
    ],
]); ?>