<?php $this->headTitle('Newsletter Preferences') ?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'action' => $this->url('newsletter/update'),
]); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?=$this->translate('Edit Newsletter Preferences');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->form($this->form);?>
    </div>
</div>
